#include <stdio.h>

/*
 * Project Euler Problem 2
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous 
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */

 int main(void)
 {
 	//
 	int sum  = 0; 
 	int curr = 2;
 	int prev = 1;
 	int temp;		//only used when setting the next fibonacci number
 	while(curr <= 4000000)
 	{
 		//if even, add to sum
 		if(curr % 2 == 0) sum += curr;
 		temp = curr;
 		curr += prev;
 		prev = temp;
 	}
 	printf("Sum = %d\n", sum);
 	return 0;
 }